### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by simonnelli** [johannrichard/homebridge-dingz#8]
I see ETIMEDOUT intermittently in the log. Don't see any issue on my network leading to this.

```
[5/25/2020, 5:54:58 PM] [dingz] Update accessory -> Check for changed config.
[5/25/2020, 6:25:30 PM] [dingz] Update accessory -> Check for changed config.
[5/25/2020, 7:22:28 PM] [dingz] Update accessory -> Check for changed config.
[5/25/2020, 8:22:28 PM] [dingz] Update accessory -> Check for changed config.
[5/25/2020, 9:22:28 PM] [dingz] Update accessory -> Check for changed config.
[5/25/2020, 9:55:51 PM] [Sonos] Studio Sonos: get Remaining Duration return 0s
[5/25/2020, 10:22:28 PM] [dingz] Update accessory -> Check for changed config.
[5/25/2020, 11:22:28 PM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 12:22:28 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 1:22:28 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 2:04:45 AM] [dingz] Error: Error: connect ETIMEDOUT 192.168.227.12:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.227.12',
  port: 80,
  config: {
    url: 'http://192.168.227.12/api/v1/motion',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Token: '',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'http:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/v1/motion',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.227.12',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/v1/motion'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /api/v1/motion HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Token: \r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: 192.168.227.12\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/v1/motion',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.227.12/api/v1/motion',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
(node:2635) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'success' of undefined
    at /homebridge/node_modules/homebridge-dingz/src/dingzAccessory.ts:862:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2635) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[5/26/2020, 2:22:29 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 3:22:29 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 4:22:29 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 5:22:29 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 6:04:37 AM] [dingz] Error: Error: connect ETIMEDOUT 192.168.227.12:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.227.12',
  port: 80,
  config: {
    url: 'http://192.168.227.12/api/v1/motion',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Token: '',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'http:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/v1/motion',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.227.12',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/v1/motion'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /api/v1/motion HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Token: \r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: 192.168.227.12\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/v1/motion',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.227.12/api/v1/motion',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
(node:2635) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'success' of undefined
    at /homebridge/node_modules/homebridge-dingz/src/dingzAccessory.ts:862:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[5/26/2020, 6:22:29 AM] [dingz] Update accessory -> Check for changed config.
[5/26/2020, 7:22:29 AM] [dingz] Update accessory -> Check for changed config.
```

**Comment by johannrichard** [comment]
Thanks for reporting. This is "expected" behavior: The motion sensor is polled quite often and sometimes these requests collide with other requests made to the DingZ (e.g. to check for status changes of the outputs, not seen in the log). This can currently lead to too many concurrent calls to the DingZ and a kind of "overload" of the DingZ which causes the timeout. 

Upcoming releases should better balance this polling and I will probably offer a setting which allows you to choose whether you want to poll for motion or let the DingZ inform Homebridge actively with a "push".  The current dev version I use at home is much more robust in that respect and should produce less errors of that kind.
